### PR TITLE
Replace external imgur/gyazo links with intra-repository links, and update the README

### PR DESCRIPTION
**Pull request by coderbot16**
This PR mirrors some banners from Imgur / Gyazo into the repository. It also mirrors the README from CurseForge, leaving it in raw HTML format.

# Rationale

* Hosting sites like Imgur and Gyazo have little incentive to continue hosting our images far into the future. For examples of where this has happened before, see [TinyPic](http://tinypic.com/), or go to the [ExtrabiomesXL Wiki](https://github.com/ExtrabiomesXL/ExtrabiomesXL/wiki/List-of-Biomes) and count all of the broken or tampered-with images.
* However, checking the images into Git ensures that they are adequately archived and will always be accessible to anyone who has a copy of the repository, and without an internet connection.
* While GitHub proxies image requests to prevent tracking, other sites like CurseForge do not. Therefore, each person who views our images can be potentially fingerprinted and/or tracked by Imgur.

# Downsides

* This increases the size of the repository by quite a bit. taking it from about 7 MB to around 10 MB. However, this increase isn't too significant in the grand scheme of things.

### CODE REVIEW

**Review by NeusFear — CHANGES_REQUESTED** [review]
We should store these images on the wiki repo, not the mod repo

**Comment by coderbot16** [comment]
That is an option, however I chose to store the images in the mod repo for a few reasons:

* Storing them on the mod repo allows the README links to be relative, meaning that they'll work just fine with cloned repos (without actually needing to fetch the image from the internet).
* Only one of these images (the Terrestria banner) is actually used by both the wiki repo and the mod repo. I think it makes more sense to store the images in the repositories where they are used.
* While having them on the mod repo increases its size, the size increase is not substantial, and only has an impact when someone needs to re-clone the entire repository. Though our CI currently does this, it's probably possible for it to do a more simple `git pull` each time too.

**Review by NeusFear — APPROVED** [review]
Makes sense to me. Sounds good.

**Comment by coderbot16** [comment]
Great, thanks!

**Pull request merged**
