### PR TITLE
Fix misspelling of Outback Bushland

### PR DESCRIPTION
**Pull request by NeeEoo**

### CODE REVIEW

**Comment by Prospector** [comment]
Not a misspelling, it's a different word.

**Comment by NeeEoo** [comment]
When i got to the outback bushland biome with the minimap mod it showed the language key instead of the value. The key was "biome.terrestria.outback_bushland"

**Comment by Prospector** [comment]
My mistake, hm I thought the biome was supposed to be a brushland, but all the code references call it a bushland. @NeusFear?

**Comment by NeusFear** [comment]
I believe we decided on one name but when it was originally coded it was the other name. I don’t remember which one was the name we decided on.

**Review by NeusFear — CHANGES_REQUESTED** [review]
I think you are correct in this change, I just merged in 4 more lang files and if you dont mine updating their keys I'll go ahead and merge this in.

**Comment by NeeEoo** [comment]
I think i did it correctly.

**Comment by NeusFear** [comment]
Thank you!

**Pull request merged**
