### PR TITLE
Add common tags to basalt blocks

### PR DESCRIPTION
**Pull request by Sturmlilie**
For compatibility with TechReborn; see https://github.com/TechReborn/TechReborn/pull/2091

### CODE REVIEW

**Comment by Prospector** [comment]
I guess the one thing that makes this tricky is that in 1.16 we renamed basalt to Volcanic Rock to not conflict with vanilla's basalt. Not sure what exactly we should do here

**Comment by Sturmlilie** [comment]
Hmm you're right, people will not get the connection that your volcanic rock grinds into basalt dust. At the same time vanilla is soon going to have more basalt than anyone can carry, with the caveat that it's only available via the nether.
Then again, anyone with REI installed can instantly find out what grinds into basalt dust.

**Comment by coderbot16** [comment]
I think it would will be reasonable to treat volcanic rock like basalt even after the name change.

**Comment by coderbot16** [comment]
It might still make sense to have Volcanic Rock grind into Basalt Dust still.

**Comment by coderbot16** [comment]
Oops, didn't notice that this was superseded by https://github.com/TerraformersMC/Terrestria/pull/117.

**Comment by coderbot16** [comment]
Uh, please disregard the above mess. I think this change makes sense, but it should probably be targeted on 1.16

**Comment by NeusFear** [comment]
@Sturmlilie would you mind updating this PR to 1.16, if not I'll go ahead and close the PR

**Comment by Sturmlilie** [comment]
Tested with latest Tech Reborn for 1.16.1.

**Review by coderbot16 — APPROVED** [review]
I think this is a good change. Perhaps we could have a separate `terrestria:volcanic_rock` tag and then include that tag in the `c:basalt` tag, but that's not strictly needed.

**Comment by Sturmlilie** [comment]
Just a heads up, there are problems with tags on latest MC versions. See: https://github.com/TechReborn/RebornCore/issues/159

**Comment by NeusFear** [comment]
@Sturmlilie is this just the in-dev issue?

**Comment by Sturmlilie** [comment]
@NeusFear not sure what "in-dev" refers to; we've had multiple people hop on the TechReborn discord and report their Blockus compat being broken. It means that even if this PR gets merged, until the tag issue gets fixed, Terrestria basalt will presumably not be grindable in TR.

**Comment by NeusFear** [comment]
in-dev means when launching the game from the development environment as opposed to using a built jar as a mod to the obfuscated game.

**Comment by NeusFear** [comment]
I think it should be fine

**Comment by Sturmlilie** [comment]
> in-dev means when launching the game from the development environment as opposed to using a built jar as a mod to the obfuscated game.

I pretty much never use this loom feature.

**Pull request merged**
