### PR TITLE
LambdaBetterGrass support

### PR DESCRIPTION
**Pull request by magneticflux-**

### CODE REVIEW

**Comment by magneticflux-** [comment]
Current state:

**Comment by gniftygnome** [comment]
This is really cool.  I see it's marked as a draft; do you have more in progress I should wait for?

**Comment by magneticflux-** [comment]
Yep, right now I'm wrestling with fences to get layers (snow, ash, leaves, sculk, etc.) to appear inside them like vanilla fences do.

**Comment by magneticflux-** [comment]
Got it:


Now I just need to apply the template to the rest of the layer-able blocks. (buttons, fence gates, pressure plates, etc.)

**Comment by magneticflux-** [comment]
Layer support! (with vanilla blocks throughout for comparison)

**Comment by magneticflux-** [comment]
I used https://gist.github.com/magneticflux-/91a9f6183c8ac69560f49c7acaf1eef7 to generate the layer definitions in bulk.

**Comment by gniftygnome** [comment]
On its way out to Modrinth (and that other one).  Thanks again!

**Pull request merged**
