### PR TITLE
Completely refactor biome registration, split it and add configurability

### PR DESCRIPTION
**Pull request by coderbot16**
Note: This will break every branch touching TerrestriaBiomes, no way to get around this; in the future, it will prevent merge conflicts when multiple branches add biomes

### CODE REVIEW

**Comment by NeusFear** [comment]
All issues I had with it were talked about in discord. Looks good to merge!

**Comment by coderbot16** [comment]
I assume you already looked over the code? Just want to make sure I didn't make any glaring mistakes

**Comment by NeusFear** [comment]
Yes, I looked over it as the commits came in.

**Comment by coderbot16** [comment]
Alright, sounds good. Will merge :ok_hand:

**Pull request merged**
